name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: 'latest'

      - name: Compile Notebook.typ to PDF
        run: typst compile Notebook.typ

      - name: Upload PDF as artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: Notebook-${{ github.sha }}
          path: Notebook.pdf
          retention-days: 90

      - name: Upload PDF to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: Notebook.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
